# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0004_auto_20170702_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
