# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0005_auto_20170702_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='city_are_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('area_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='samapp.areas')),
                ('city_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='samapp.cities')),
            ],
        ),
        migrations.CreateModel(
            name='dress_service_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_id', models.CharField(max_length=50)),
                ('service_id', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dresses', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='excess_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('laundry_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='samapp.laundries')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('dress_service_map_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='samapp.dress_service_map')),
                ('excess_cost_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='samapp.excess_cost')),
                ('laundry_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='samapp.laundries')),
            ],
        ),
        migrations.CreateModel(
            name='sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectors', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
            ],
        ),
    ]
